### ISSUE TITLE
Patch bugs neatvi

### ISSUE THREAD

**Issue by kyx0r** [juliusHuelsmann/st-history#12]
More info here: 
https://github.com/aligrudi/neatvi/issues/16

This is due to possibly how the history is handled in tresize() but definitely regression is there.
For now I will refrain from using this.

*tested with upstream clean neatvi build & clean st build + st-vimBrowse-latestRelease-9ba7ecf.diff

**Comment by juliusHuelsmann** [comment]
Thanks for reporting this issue; yes, there is be a bug with the `tresize` function which I encountered previously and which could cause this; I won't be able to have a look a this in the next two months, so in case you have the time to fix this issue, your contribution would be very welcome

**Comment by juliusHuelsmann** [comment]
should be fixed in the latest version.
