### ISSUE TITLE
Is thera a way move by mouse when into normal mode?

### ISSUE THREAD

**Issue by zaiqiang-dong** [juliusHuelsmann/st-history#19]
Is thera a way move by mouse when into normal mode?

**Comment by juliusHuelsmann** [comment]
Hey :) 

I think with the latest version of the history patch this should be possible in normal mode; in normal mode you can click a location, which should subsequently become active. If you click twice, the word underneath is selected and copied into clipboard, I think if you click three times it copies the entire line. 

In insert mode this is currently not possible, might be cool to add that (+ maybe a way to leave normal mode & keep the current location). But I think when I had a look at this initially, the naive implementation seemed like a bit more work / error prone than I expected, because we not only need the location on screen, but also extract the current location inside the command buffer. But that's quite a while ago, I am not too sure if I remember correctly

**Comment by juliusHuelsmann** [comment]
or do you mean scroll up and down? That is currently not implemented, but should be an easy-ish addition (that you could also patch on top of the vim patch). 

for moving up you can use:
```c++
historyMove(0, -(int)state.m.c, 0);
```

motion down is without the `-`. 

you can theoretically add this to the shortcuts table, but that would be executed even if not in normal mode, so probably you should implement it in `executeMotion` or `kPressHist;` (wherever you have access to the input produced by spinning the weel up / down resp).

If you want help on this I can look into this at some point in the future and come back to you about this in this issue in the next couple of days / weeks

**Comment by zaiqiang-dong** [comment]
I try historyMove, but it can not work ok. it can be determined that the function has been called by the log "called", but it cannot be moved. change is :
` git diff
diff --git a/config.def.h b/config.def.h
index 4476057..1451bae 100644
--- a/config.def.h
+++ b/config.def.h
@@ -204,13 +204,12 @@ static uint forcemousemod = ShiftMask;
  */
 static MouseShortcut mshortcuts[] = {
     /* mask                 button   function        argument       release */
-    /*
-     * { XK_ANY_MOD,           Button2, selpaste,       {.i = 0},      1 },
-     * { ShiftMask,            Button4, ttysend,        {.s = "\033[5;2~"} },
-     * { XK_ANY_MOD,           Button4, ttysend,        {.s = "\031"} },
-     * { ShiftMask,            Button5, ttysend,        {.s = "\033[6;2~"} },
-     * { XK_ANY_MOD,           Button5, ttysend,        {.s = "\005"} },
-     */
+    // { XK_ANY_MOD,           Button2, selpaste,       {.i = 0},      1 },
+    // { ShiftMask,            Button4, ttysend,        {.s = "\033[5;2~"} },
+    // { XK_ANY_MOD,           Button4, ttysend,        {.s = "\031"} },
+    // { ShiftMask,            Button5, ttysend,        {.s = "\033[6;2~"} },
+    { XK_ANY_MOD,           Button4, mouseHistoryScrollUp,        {.s = "\031"} },
+    { XK_ANY_MOD,           Button5, mouseHistoryScrollUp,        {.s = "\005"} },
 };
 
 /* Internal keyboard shortcuts. */
diff --git a/normalMode.c b/normalMode.c
index f0c7e30..68c1c88 100644
--- a/normalMode.c
+++ b/normalMode.c
@@ -282,3 +282,8 @@ void historyPreDraw() {
     op = (Pos){.p = {term.c.x, term.c.y, 0}};
     historyOpToggle(-1, 0);
 }
+
+void mouseHistoryScrollUp() {
+    printf("called\n");
+    historyMove(0, (int)state.m.c, 0);
+}
diff --git a/normalMode.h b/normalMode.h
index eb77484..907a1b3 100644
--- a/normalMode.h
+++ b/normalMode.h
@@ -6,3 +6,4 @@ void historyOpToggle(int, int);
 typedef enum {failed=0, success=1, exitMotion=2, exitOp=3, finish=4} ExitState;
 ExitState kPressHist(char const *txt, size_t len, int ctrl, KeySym const *kSym);
 ExitState pressKeys(char const* s, size_t e);
+void mouseHistoryScrollUp();
`

**Comment by zaiqiang-dong** [comment]
historyMove work ok for me.Thanks.
